name: Check & Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  POETRY_NO_INTERACTION: 1
  POETRY_VERSION: 1.4.0
  POETRY_VIRTUALENVS_IN_PROJECT: 1
  PRE_COMMIT_VERSION: "2.17.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: super-linter/super-linter
